[package]
name = "gignore"
version = "0.1.0"
authors = ["Kirill <stealer-mail@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0.2"
git2 = "0.13.6"
