[package]
name = "gignore"
version = "0.1.0"
authors = ["Kirill <stealer-mail@mail.ru>"]
edition = "2018"
default-rn = "gignore"


[build-dependencies]
git2 = "0.13.6"
dirs = "2.0.2"

[dependencies]
dirs = "2.0.2"
